# Generated by Django 6.0.7 on 2026-07-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_gatevalidationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('db_type', models.CharField(max_length=50)),
                ('conn_str', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_096de0_idx',
            old_name='core_auditl_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_actor_725736_idx',
            old_name='core_auditl_actor_idx',
        ),
        migrations.RenameIndex(
            model_name='gatevalidationlog',
            new_name='core_gateva_pipelin_06e80c_idx',
            old_name='core_gateva_pipelin_idx',
        ),
        migrations.RenameIndex(
            model_name='schemasnapshot',
            new_name='core_schema_pipelin_93d9ea_idx',
            old_name='core_schema_pipelin_idx',
        ),
        migrations.AddField(
            model_name='connectionprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connection_profiles', to='core.organization'),
        ),
    ]
