# Generated by Django 5.0.14 on 2026-07-07 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('db_type', models.CharField(max_length=50)),
                ('conn_str', models.CharField(max_length=1000)),
                ('schema', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255)),
                ('cron', models.CharField(default='0 0 * * *', max_length=50)),
                ('cron_text', models.CharField(default='Daily preset', max_length=255)),
                ('alerts', models.JSONField(default=dict)),
                ('status', models.CharField(default='Clean', max_length=50)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('lock_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('schema_map', models.JSONField(default=dict)),
                ('logs', models.JSONField(default=list)),
                ('compliance_history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(default='operator', max_length=50)),
                ('permissions', models.JSONField(default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
            ],
        ),
    ]
